hmcts/dlrm-data-ingest-infra

- azure-pipelines.yaml
- components/landing/init.tf
- environments/sbox/sbox.tfvars
> feat: test pipeline

- components/landing/data-landing-zone.tf
- components/management/data-mgmt-zone.tf
> fix: shorten name

- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
N/A
Destroy additional landing zones used for testing the pipeline/deployment process.
> feat: destroy additional test landing zones

- azure-pipelines.yaml
- components/management/data-mgmt-zone.tf
- components/management/inputs-optional.tf
- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DIP-48
> feat: added mgmt kv access policy for reader group

- components/landing/inputs-required.tf
- components/landing/interpolated-defaults.tf
- components/landing/self-hosted-runner.tf
- environments/sbox/sbox.tfvars
> feat: added GitHub self-hosted runner

- components/landing/data-landing-zone.tf
- components/landing/inputs-required.tf
- components/landing/self-hosted-runner.tf
- environments/sbox/sbox.tfvars
> feat: extend address space

- components/landing/data-landing-zone.tf
- components/landing/inputs-required.tf
- environments/sbox/sbox.tfvars
> fix: update roles for ingest00 in sbox

- environments/sbox/sbox.tfvars
> feat: comment out ingest00

- environments/sbox/sbox.tfvars
> fix: redeploy legacy sql

- components/landing/inputs-required.tf
- environments/sbox/sbox.tfvars
> feat: added pip for legacy VMs

- components/landing/inputs-required.tf
- environments/sbox/sbox.tfvars
> feat: deploy new legacy vm to test RDP from pip

- components/landing/data-landing-zone.tf
> fix: correct module ref

- environments/sbox/sbox.tfvars
> feat: spin out new landing zone in sbox

- components/landing/logic.tf
- modules/ipkit_logic/app-insights.tf
- modules/ipkit_logic/app-service-plan.tf
- modules/ipkit_logic/init.tf
- modules/ipkit_logic/inputs-optional.tf
- modules/ipkit_logic/inputs-required.tf
- modules/ipkit_logic/interpolated-defaults.tf
- modules/ipkit_logic/logic-app.tf
- modules/ipkit_logic/rbac.tf
- modules/ipkit_logic/storage-account.tf
> feat: added logic to tf

- components/landing/data-landing-zone.tf
- components/landing/interpolated-defaults.tf
add auto shutdown tags to ingeest VMS
> add autoshutdown tag to ingest VM

- components/management/data-mgmt-zone.tf
- environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18705
I didnt add event hub to stg so adding now
this is done on prod and sbox
> Dtspo 18705 eventhub

- components/landing/data-landing-zone.tf
- components/landing/init.tf
- components/landing/inputs-optional.tf
- components/management/data-mgmt-zone.tf
- components/management/inputs-optional.tf
- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
- modules/ipkit_logic/logic-app.tf
https://tools.hmcts.net/jira/browse/DTSPO-18899
Installing Azure monitor Agent to the nonprod VMs
ingest00-legacy-sql-sbox
ingest00-legacy-sql-stg
> DTSPO-18899 -  installing Azure monitor Agent to the nonprod VMs

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18901
Adding AMA to the following prod VMs
ingest00-legacy-sql-prod
-->
> DTSPO-18901 - deploying AMA to the prod VMs

- components/management/data-mgmt-zone.tf
- components/management/inputs-optional.tf
- environments/sbox/sbox.tfvars
See [DTSPO-22571](https://tools.hmcts.net/jira/browse/DTSPO-22571)
> feat: deploy 01 zone in sandbox

- components/management/data-mgmt-zone.tf
- components/management/inputs-optional.tf
- components/management/inputs-required.tf
- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
See [DTSPO-24027](https://tools.hmcts.net/jira/browse/DTSPO-24027)
Testing creation/inclusion of multiple eventhubs in single namespace
> Testing inclusion of multiple eventhubs

- environments/sbox/sbox.tfvars
See [DTSPO-24027](https://tools.hmcts.net/jira/browse/DTSPO-24027)
Max throughput units amended as causing tf apply to fail
> Max throughput units amended as causing tf apply to fail

- environments/sbox/sbox.tfvars
See [DTSPO-24027](https://tools.hmcts.net/jira/browse/DTSPO-24027)
eventhub capacity amended as causing tf apply to fail
> eventhub capacity amended as causing tf apply to fail

- environments/sbox/sbox.tfvars
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> fix: add test zone

- components/management/data-mgmt-zone.tf
- components/management/inputs-optional.tf
- environments/sbox/sbox.tfvars
See [DTSPO-24027](https://tools.hmcts.net/jira/browse/DTSPO-24027)
Removed previously added max_throughput_units as causing tf apply failure
> Removed previously added max_throughput_units as causing tf apply failure

- components/landing/data-landing-zone.tf
- components/landing/inputs-required.tf
- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> feat: sftp storage

- components/landing/interpolated-defaults.tf
- components/landing/role-assignments.tf
- environments/sbox/sbox.tfvars
See [DTSPO-24907](https://tools.hmcts.net/jira/browse/DTSPO-24907)
Add role to allow private dns pipeline to add vnet links to dns zones
> DTSPO-24907 - Add role for dns zone link in sbox

- components/landing/data-landing-zone.tf
- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
N/A
Update landing zone module ref to main.
> fix: correct landing zone module ref

- components/landing/data-landing-zone.tf
- components/landing/init.tf
- components/landing/interpolated-defaults.tf
- components/management/init.tf
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
> fix: shrink mysql delegated and expand services

- environments/sbox/sbox.tfvars
See [DTSPO-25052](https://tools.hmcts.net/jira/browse/DTSPO-25052)
> feat: added 02 sbox zone

- azure-pipelines.yaml
- components/landing/data-landing-zone.tf
- components/landing/inputs-required.tf
- environments/prod/prod.tfvars
See [DTSPO-24907](https://tools.hmcts.net/jira/browse/DTSPO-24907)
Adding prod stage for ai component
Fixing issue in prod landing stage where snapshot is 500GB instead of 127GB
> DTSPO-24907 - Add prod ai stage

- environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25855
Isabella.O'Hara@HMCTS.NET added to the Prod Landing zone.
> add Isabella to data ingest 00

- environments/prod/prod.tfvars
- environments/sbox/sbox.tfvars
- environments/stg/stg.tfvars
See [DTSPO-26373](https://tools.hmcts.net/jira/browse/DTSPO-26373)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> feat: added MoJo Prisma Access IP range

- environments/prod/prod.tfvars
- environments/stg/stg.tfvars
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> feat: increase size of legacy sql vm
